### ISSUE TITLE
E3001 Missing properties raised as an error when they're not required

### ISSUE THREAD

**Issue by viraptor** [awslabs/cfn-python-lint#266]
*cfn-lint version: 0.4.2*

*Description of issue.*

An error about missing properties is not always useful. There are resources which don't necessarily need properties.

Please provide as much information as possible:
* Template linting issues:
```
    "WaitCondition": {
      "Type": "AWS::CloudFormation::WaitCondition",
      "CreationPolicy": {
        "ResourceSignal": {
          "Timeout": "PT15M",
          "Count": {
            "Ref": "TargetCapacity"
          }
        }
      }
    }
```
Getting `E3001 Properties not defined for resource WaitCondition`

* Feature request:

I'm not sure if there's a list of resources which don't need properties in many situations. S3 buckets and WaitCondition seem like good candidates for not raising this.
[AWS docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html) say:
> Use the optional Parameters section to customize your templates.
so it doesn't sound like it needs to be provided.

**Comment by kddejong** [comment]
@cmmeyer this one may be with you too.  The reason this is showing up is because according to the spec there are required properties.
```
"AWS::CloudFormation::WaitCondition": {
      "Attributes": {
        "Data": {
          "PrimitiveType": "Json"
        }
      },
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waitcondition.html",
      "Properties": {
        "Count": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waitcondition.html#cfn-waitcondition-count",
          "PrimitiveType": "Integer",
          "Required": false,
          "UpdateType": "Mutable"
        },
        "Handle": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waitcondition.html#cfn-waitcondition-handle",
          "PrimitiveType": "String",
          "Required": true,
          "UpdateType": "Mutable"
        },
        "Timeout": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waitcondition.html#cfn-waitcondition-timeout",
          "PrimitiveType": "String",
          "Required": true,
          "UpdateType": "Mutable"
        }
      }
    },
```

**Comment by kddejong** [comment]
If the spec didn't have required attributes `Properties` wouldn't be required.
```
➜  cat test.yaml
---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  myBucket:
    Type: AWS::S3::Bucket
➜  cfn-lint test1.yaml
➜  echo $?
0
```

**Comment by kddejong** [comment]
Tested this and looks like a special case related to WaitConditions.   We are probably going to have to come up with an exception process for `E3001` as the Spec Properties are required if there isn't a `CreationPolicy`.

Looks like there is a Warning rule that should be added for making sure people are using `CreationPolicy` when doing ASGs and Instances instead of doing a `Ref` to a `AWS::CloudFormation::WaitCondition`.

**Comment by cmmeyer** [comment]
I had to play some catch-up on this one.  Historically, it wouldn't make any sense to create a WaitCondition w/o a handle, since it wouldn't be listening to anything.  CreationPolicies give it another way to "listen" which obviates the need for the Handler.  Looks like no one ever took this into account.  I'm going to file it as a Resource Spec/Doc bug.  

Do we want the patch in the meantime? This would theoretically be covered under current lgoic if i get the spec updated, correct?

**Comment by kddejong** [comment]
I don't mind patching this for now but we should probably create a followup issue to fix it when the spec is updated.  Since the CreationPolicy is a resource level item what would the updates to the spec be?  To switch the required properties to no longer be required?

**Comment by cmmeyer** [comment]
Update would be to remove the requirement -- this is typically how this is handled since the current spec doesn't support complex *or* logic. 

I've created #278 to track the spec update bug.
