### ISSUE TITLE
AttributeError: 'LambdaRuntime' object has no attribute 'resource_property_types'

### ISSUE THREAD

**Issue by viraptor** [awslabs/cfn-python-lint#637]
*cfn-lint version: 0.13.1*

*Description of issue.*

At startup, I get failure:

```
Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/cfnlint/__main__.py", line 28, in main
    (args, filenames, formatter) = cfnlint.core.get_args_filenames(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/cfnlint/core.py", line 123, in get_args_filenames
    rules = cfnlint.core.get_rules(config.append_rules, config.ignore_checks, config.include_checks)
  File "/usr/local/lib/python3.7/site-packages/cfnlint/core.py", line 96, in get_rules
    RulesCollection.create_from_directory(rules_dir))
  File "/usr/local/lib/python3.7/site-packages/cfnlint/__init__.py", line 330, in create_from_directory
    result.rules = cfnlint.helpers.load_plugins(os.path.expanduser(rulesdir))
  File "/usr/local/lib/python3.7/site-packages/cfnlint/helpers.py", line 233, in load_plugins
    obj = clazz()
  File "/usr/local/lib/python3.7/site-packages/cfnlint/rules/parameters/LambdaRuntime.py", line 37, in __init__
    self.resource_property_types.append(resoruce_type_spec)
AttributeError: 'LambdaRuntime' object has no attribute 'resource_property_types'
```

Last version which worked was `0.10.3`

**Comment by cmmeyer** [comment]
Hi @viraptor -- in 0.11.0 we changed how we lint resource value. We moved from resource specific rules to an enriched resource specification that includes value information. As part of that change (PR #536) we removed the `LambdaRuntime.py` rule along with several others, since these are now handled by the common value check rule.

There shouldn't be any references to the LambdaRuntime class in the newer codebase. You may have some old linter code hanging around. I would suggest trying a clean uninstall/reinstall to get things back in working order.

Tangentially, looks like we have an ugly typo in our codebase (`resoruce_type_spec`).  It's always used as a local variable, but it shows up several times in the code base (copypasta I suspect).

I'll cut a separate issue for that, but do let me know if a clean install resolves your problem.

**Comment by viraptor** [comment]
Weird... Uninstalling did help. I got:
```
Uninstalling cfn-lint-0.10.2:
  Would remove:
    /usr/local/bin/cfn-lint
    /usr/local/lib/python3.7/site-packages/cfn_lint-0.10.2.dist-info/*
    /usr/local/lib/python3.7/site-packages/cfnlint/*
  Would not remove (might be manually added):
    /usr/local/lib/python3.7/site-packages/cfnlint/decode/str_node.py
    /usr/local/lib/python3.7/site-packages/cfnlint/rules/functions/IfExist.py
Proceed (y/n)? y
  Successfully uninstalled cfn-lint-0.10.2
```
Although I used only the standard pip installation.
🤷‍♂️

**Comment by cmmeyer** [comment]
Glad that helped. Sorry for the weirdness. I mentioned uninstall/reinstall because I noticed a few stray `.pyc` files floating around in my installation as well. 

Ok to close?
